name: point_in_time_fundamentals
version: "0.1.0"
config-version: 2
profile: point_in_time_fundamentals

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests/data_tests"]

models:
  point_in_time_fundamentals:
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: table
      +schema: intermediate

seeds:
  point_in_time_fundamentals:
    +schema: reference
    concept_map:
      +column_types:
        priority: integer
